# Generated by Django 5.2.6 on 2025-09-10 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0002_problemreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='teacher_materials',
            field=models.FileField(blank=True, help_text='Материалы для преподавателя (видны только преподавателю)', null=True, upload_to='lesson_teacher_materials/'),
        ),
    ]
