# Generated by Django 5.2.6 on 2025-09-10 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0003_lesson_teacher_materials'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='completion_confirmed_at',
            field=models.DateTimeField(blank=True, help_text='Когда урок был подтвержден обеими сторонами', null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='student_confirmed_completion',
            field=models.BooleanField(default=False, help_text='Ученик подтвердил посещение урока'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='teacher_confirmed_completion',
            field=models.BooleanField(default=False, help_text='Преподаватель подтвердил проведение урока'),
        ),
    ]
