# Generated by Django 5.2.5 on 2025-09-11 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0005_lessonfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonfile',
            name='file_size',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lessonfile',
            name='is_teacher_material',
            field=models.BooleanField(default=False),
        ),
    ]
