# Generated by Django 5.2.5 on 2025-09-11 13:30

import django.core.validators
import scheduling.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0006_alter_lessonfile_file_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonfile',
            name='file',
            field=models.FileField(upload_to=scheduling.models.get_unique_lesson_file_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'txt', 'jpg', 'png', 'zip'])]),
        ),
    ]
