# Generated by Django 5.2.6 on 2025-09-11 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0007_alter_lessonfile_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='original_end_time',
            field=models.DateTimeField(blank=True, help_text='Изначальное время окончания до переноса', null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='original_start_time',
            field=models.DateTimeField(blank=True, help_text='Изначальное время начала до переноса', null=True),
        ),
    ]
