# Generated by Django 5.2.6 on 2025-09-10 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0001_initial'),
        ('scheduling', '0003_lesson_teacher_materials'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='lesson',
            field=models.ForeignKey(blank=True, help_text='Связанное занятие (необязательно)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='scheduling.lesson'),
        ),
    ]
