# Generated by Django 5.2.6 on 2025-09-13 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0005_alter_assignment_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('lesson_created', 'Lesson Created'), ('lesson_updated', 'Lesson Updated'), ('lesson_reminder_24h', '24h Lesson Reminder'), ('lesson_reminder_1h', '1h Lesson Reminder'), ('lesson_feedback_reminder', 'Lesson Feedback Reminder'), ('assignment_assigned', 'Assignment Assigned'), ('assignment_due_soon', 'Assignment Due Soon'), ('assignment_overdue', 'Assignment Overdue'), ('assignment_submitted', 'Assignment Submitted'), ('assignment_reviewed', 'Assignment Reviewed')], max_length=30),
        ),
    ]
